
read.gbif <- function(file, ...) {
    read.csv(file = file, sep = "\t", quote = NULL, ...)
}

filter_fields.gbif <- function(x, select = gbif_standard_fields) {
    x[,select]
}

turn_to_array_string <- function(s) {
    paste("c(",paste(paste0("'",s,"'"), collapse=", "),")")
}


standard_fields <- c(
    'data_source',
    'barcode',
    'collectionCode',
    'catalogNumber',
    'scientificName',
    'kingdom',
    'family',
    'genus',
    'year',
    'month',
    'day',
    'country',
    'stateProvince',
    'county',
    'locality',
    'institutionCode',
    'basisOfRecord',
    'identifiedBy',
    'yearIdentified',
    'monthIdentified',
    'dayIdentified',
    'verbatimLatitude',
    'verbatimLongitude',
    'collectionID',
    'specificepithet',
    'recordedBy',
    'decimalLongitude',
    'decimalLatitude',
    'modified',
    'scientificNameAuthorship',
    'recordNumber',
    'minimumelevationinmeters',
    'maximumelevationinmeters',
    'coordinatePrecision',
    'phylum',
    'order',
    'individualcount',
    'continentocean',
    'class',
    'infraspecificepithet',
    'preparationtype',
    'typeStatus',
    'fieldnumber',
    'previouscatalognumber',
    'minimumdepthinmeters',
    'maximumdepthinmeters',
    'downloadedFrom',
    'municipality',
    'dateIdentified',
    'acceptedScientificName',
    'bibliographicCitation',
    'countryCode',
    'datasetID',
    'datasetName',
    'eventDate',
    'fieldNotes',
    'habitat',
    'identificationRemarks',
    'latitude',
    'longitude',
    'taxonomicStatus',
    'taxonRank',
    'type',
    'verbatimElevation',
    'verbatimEventDate',
    'verbatimLocality',
    'collectionCode.new',
    'collectionObs',
    'recordedBy.new',
    'recordNumber.new',
    'year.new',
    'identifiedBy.new',
    'yearIdentified.new',
    'recordedBy.aux',
    'last.name',
    'identifiedBy.aux',
    'country.new',
    'stateProvince.new',
    'municipality.new',
    'locality.new',
    'locality.scrap',
    'resol.orig',
    'loc',
    'loc.correct',
    'latitude.gazetteer',
    'longitude.gazetteer',
    'resolution.gazetteer' )

gbif_standard_fields <- c(
    'gbifID',
    # 'abstract',
    # 'accessRights',
    # 'accrualMethod',
    # 'accrualPeriodicity',
    # 'accrualPolicy',
    # 'alternative',
    # 'audience',
    # 'available',
    # 'bibliographicCitation',
    # 'conformsTo',
    # 'contributor',
    # 'coverage',
    # 'created',
    # 'creator',
    # 'date',
    # 'dateAccepted',
    # 'dateCopyrighted',
    # 'dateSubmitted',
    # 'description',
    # 'educationLevel',
    # 'extent',
    # 'format',
    # 'hasFormat',
    # 'hasPart',
    # 'hasVersion',
    # 'identifier',
    # 'instructionalMethod',
    # 'isFormatOf',
    # 'isPartOf',
    # 'isReferencedBy',
    # 'isReplacedBy',
    # 'isRequiredBy',
    # 'isVersionOf',
    # 'issued',
    # 'language',
    # 'license',
    # 'mediator',
    # 'medium',
    # 'modified',
    # 'provenance',
    # 'publisher',
    # 'references',
    # 'relation',
    # 'replaces',
    # 'requires',
    # 'rights',
    # 'rightsHolder',
    # 'source',
    # 'spatial',
    # 'subject',
    # 'tableOfContents',
    # 'temporal',
    # 'title',
    # 'type',
    # 'valid',
    # 'institutionID',
    # 'collectionID',
    # 'datasetID',
    # 'institutionCode',
    # 'collectionCode',
    'datasetName',
    # 'ownerInstitutionCode',
    'basisOfRecord',
    'informationWithheld',
    'dataGeneralizations',
    # 'dynamicProperties',
    'occurrenceID',
    'catalogNumber',
    'recordNumber',
    'recordedBy',
    'recordedByID',
    # 'individualCount',
    # 'organismQuantity',
    # 'organismQuantityType',
    # 'sex',
    # 'lifeStage',
    # 'reproductiveCondition',
    # 'behavior',
    # 'establishmentMeans',
    # 'degreeOfEstablishment',
    # 'pathway',
    'georeferenceVerificationStatus',
    'occurrenceStatus',
    # 'preparations',
    # 'disposition',
    # 'associatedOccurrences',
    # 'associatedReferences',
    # 'associatedSequences',
    # 'associatedTaxa',
    # 'otherCatalogNumbers',
    # 'occurrenceRemarks',
    # 'organismID',
    # 'organismName',
    # 'organismScope',
    # 'associatedOrganisms',
    # 'previousIdentifications',
    # 'organismRemarks',
    # 'materialSampleID',
    # 'eventID',
    # 'parentEventID',
    'fieldNumber',
    'eventDate',
    # 'eventTime',
    # 'startDayOfYear',
    # 'endDayOfYear',
    'year',
    'month',
    'day',
    'verbatimEventDate',
    # 'habitat',
    'samplingProtocol',
    # 'sampleSizeValue',
    # 'sampleSizeUnit',
    # 'samplingEffort',
    'fieldNotes',
    'eventRemarks',
    'locationID',
    # 'higherGeographyID',
    # 'higherGeography',
    # 'continent',
    # 'waterBody',
    # 'islandGroup',
    # 'island',
    'countryCode',
    'stateProvince',
    'county',
    'municipality',
    'locality',
    'verbatimLocality',
    'verbatimElevation',
    # 'verticalDatum',
    # 'verbatimDepth',
    # 'minimumDistanceAboveSurfaceInMeters',
    # 'maximumDistanceAboveSurfaceInMeters',
    # 'locationAccordingTo',
    'locationRemarks',
    'decimalLatitude',
    'decimalLongitude',
    'coordinateUncertaintyInMeters',
    'coordinatePrecision',
    'pointRadiusSpatialFit',
    'verbatimCoordinateSystem',
    # 'verbatimSRS',
    # 'footprintWKT',
    # 'footprintSRS',
    # 'footprintSpatialFit',
    'georeferencedBy',
    'georeferencedDate',
    'georeferenceProtocol',
    # 'georeferenceSources',
    'georeferenceRemarks',
    # 'geologicalContextID',
    # 'earliestEonOrLowestEonothem',
    # 'latestEonOrHighestEonothem',
    # 'earliestEraOrLowestErathem',
    # 'latestEraOrHighestErathem',
    # 'earliestPeriodOrLowestSystem',
    # 'latestPeriodOrHighestSystem',
    # 'earliestEpochOrLowestSeries',
    # 'latestEpochOrHighestSeries',
    # 'earliestAgeOrLowestStage',
    # 'latestAgeOrHighestStage',
    # 'lowestBiostratigraphicZone',
    # 'highestBiostratigraphicZone',
    # 'lithostratigraphicTerms',
    # 'group',
    # 'formation',
    # 'member',
    # 'bed',
    'identificationID',
    'verbatimIdentification',
    # 'identificationQualifier',
    'typeStatus',
    'identifiedBy',
    'identifiedByID',
    'dateIdentified',
    # 'identificationReferences',
    # 'identificationVerificationStatus',
    # 'identificationRemarks',
    'taxonID',
    # 'scientificNameID',
    # 'acceptedNameUsageID',
    # 'parentNameUsageID',
    # 'originalNameUsageID',
    # 'nameAccordingToID',
    # 'namePublishedInID',
    # 'taxonConceptID',
    'scientificName',
    'acceptedNameUsage',
    'parentNameUsage',
    'originalNameUsage',
    'nameAccordingTo',
    'namePublishedIn',
    'namePublishedInYear',
    # 'higherClassification',
    'kingdom',
    'phylum',
    'class',
    'order',
    'family',
    'subfamily',
    'genus',
    'genericName',
    'subgenus',
    'infragenericEpithet',
    'specificEpithet',
    'infraspecificEpithet',
    'cultivarEpithet',
    'taxonRank',
    'verbatimTaxonRank',
    # 'vernacularName',
    # 'nomenclaturalCode',
    'taxonomicStatus',
    # 'nomenclaturalStatus',
    'taxonRemarks',
    'datasetKey',
    # 'publishingCountry',
    # 'lastInterpreted',
    # 'elevation',
    # 'elevationAccuracy',
    # 'depth',
    # 'depthAccuracy',
    # 'distanceAboveSurface',
    # 'distanceAboveSurfaceAccuracy',
    # 'issue',
    'mediaType',
    'hasCoordinate',
    'hasGeospatialIssues',
    # 'taxonKey',
    # 'acceptedTaxonKey',
    # 'kingdomKey',
    # 'phylumKey',
    # 'classKey',
    # 'orderKey',
    # 'familyKey',
    # 'genusKey',
    # 'subgenusKey',
    # 'speciesKey',
    'species',
    'acceptedScientificName',
    'verbatimScientificName',
    # 'typifiedName',
    # 'protocol',
    # 'lastParsed',
    # 'lastCrawled',
    # 'repatriated',
    # 'relativeOrganismQuantity',
    # 'level0Gid',
    # 'level0Name',
    # 'level1Gid',
    # 'level1Name',
    # 'level2Gid',
    # 'level2Name',
    # 'level3Gid',
    # 'level3Name',
    'iucnRedListCategory'
  )

remove_fields <- function(x, to_remove = c(
    'X',
    'abstract',
    'accessRights',
    'accrualMethod',
    'accrualPeriodicity',
    'accrualPolicy',
    'alternative',
    'audience',
    'available',
    'conformsTo',
    'contributor',
    'coverage',
    'created',
    'creator',
    'date',
    'dateAccepted',
    'dateCopyrighted',
    'dateSubmitted',
    'description',
    'educationLevel',
    'extent',
    'format',
    'hasFormat',
    'hasPart',
    'hasVersion',
    'identifier',
    'instructionalMethod',
    'isFormatOf',
    'isPartOf',
    'isReferencedBy',
    'isReplacedBy',
    'isRequiredBy',
    'isVersionOf',
    'issued',
    'language',
    'license',
    'mediator',
    'medium',
    'provenance',
    'publisher',
    'references',
    'relation',
    'replaces',
    'requires',
    'rights',
    'rightsHolder',
    'source',
    'spatial',
    'subject',
    'tableOfContents',
    'temporal',
    'title',
    'valid',
    'ownerInstitutionCode',
    'dynamicProperties',
    'individualCount',
    'organismQuantity',
    'organismQuantityType',
    'sex',
    'lifeStage',
    'reproductiveCondition',
    'behavior',
    'establishmentMeans',
    'degreeOfEstablishment',
    'pathway',
    'preparations',
    'disposition',
    'associatedOccurrences',
    'associatedReferences',
    'associatedSequences',
    'associatedTaxa',
    'otherCatalogNumbers',
    'occurrenceRemarks',
    'organismID',
    'organismName',
    'organismScope',
    'associatedOrganisms',
    'previousIdentifications',
    'organismRemarks',
    'materialSampleID',
    'eventID',
    'parentEventID',
    'eventTime',
    'startDayOfYear',
    'endDayOfYear',
    'sampleSizeValue',
    'sampleSizeUnit',
    'samplingEffort',
    'higherGeographyID',
    'higherGeography',
    'continent',
    'waterBody',
    'islandGroup',
    'island',
    'verticalDatum',
    'verbatimDepth',
    'minimumDistanceAboveSurfaceInMeters',
    'maximumDistanceAboveSurfaceInMeters',
    'locationAccordingTo',
    'verbatimSRS',
    'footprintWKT',
    'footprintSRS',
    'footprintSpatialFit',
    'georeferenceSources',
    'geologicalContextID',
    'earliestEonOrLowestEonothem',
    'latestEonOrHighestEonothem',
    'earliestEraOrLowestErathem',
    'latestEraOrHighestErathem',
    'earliestPeriodOrLowestSystem',
    'latestPeriodOrHighestSystem',
    'earliestEpochOrLowestSeries',
    'latestEpochOrHighestSeries',
    'earliestAgeOrLowestStage',
    'latestAgeOrHighestStage',
    'lowestBiostratigraphicZone',
    'highestBiostratigraphicZone',
    'lithostratigraphicTerms',
    'group',
    'formation',
    'member',
    'bed',
    'identificationQualifier',
    'identificationReferences',
    'identificationVerificationStatus',
    'scientificNameID',
    'acceptedNameUsageID',
    'parentNameUsageID',
    'originalNameUsageID',
    'nameAccordingToID',
    'namePublishedInID',
    'taxonConceptID',
    'higherClassification',
    'vernacularName',
    'nomenclaturalCode',
    'nomenclaturalStatus',
    'publishingCountry',
    'lastInterpreted',
    'elevation',
    'elevationAccuracy',
    'depth',
    'depthAccuracy',
    'distanceAboveSurface',
    'distanceAboveSurfaceAccuracy',
    'issue',
    'taxonKey',
    'acceptedTaxonKey',
    'kingdomKey',
    'phylumKey',
    'classKey',
    'orderKey',
    'familyKey',
    'genusKey',
    'subgenusKey',
    'speciesKey',
    'typifiedName',
    'protocol',
    'lastParsed',
    'lastCrawled',
    'repatriated',
    'relativeOrganismQuantity',
    'level0Gid',
    'level0Name',
    'level1Gid',
    'level1Name',
    'level2Gid',
    'level2Name',
    'level3Gid',
    'level3Name',
    'NAME_0',
    'NAME_1',
    'NAME_2',
    'NAME_3',
    'NAME_4'
  )) {

  x[, !names(x) %in% to_remove]
}

# Select fields
f <-  plantR:::fieldNames
plantR_fields <- f[!is.na(f$type),c("plantr")]
extra_mine <- c("taxonRank", "verbatimScientificName", "acceptedScientificName", "species", "taxonID", "typeStatus", "recordID", "eventDate", "verbatimEventDate", "geodeticDatum", "associatedMedia",  "virtualDuplicates", "duplicates", "barcode", "downloadedFrom")
desired_fields <- union(plantR_fields, extra_mine)

#' Select fields
#'
#' A function to reduce the number of columns during data treatement
#'
#' @param x A data frame
#' @param desiredFields A list of names, ideally contained in names(x)
selectDesiredFields <- function(x, desiredFields = desired_fields) x[,intersect(names(x), desiredFields)]
